name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Doing Unit Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres 
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:

    # check out the code into the machine 
    - name: Check out code
      uses: actions/checkout@v3c
 
    # install golnag compiler
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Set up the Postgres DB
    - name: Run migrations
      run: make up

    # run unit test
    - name: Test
      run: make test 

